(function(){'use strict';
var e,g="object"===typeof __ScalaJSEnv&&__ScalaJSEnv?__ScalaJSEnv:{},l="object"===typeof g.global&&g.global?g.global:"object"===typeof global&&global&&global.Object===Object?global:this;g.global=l;var aa="object"===typeof g.exportsNamespace&&g.exportsNamespace?g.exportsNamespace:l;g.exportsNamespace=aa;l.Object.freeze(g);var ba={envInfo:g,semantics:{asInstanceOfs:2,arrayIndexOutOfBounds:2,moduleInit:2,strictFloats:!1,productionMode:!0},assumingES6:!1,linkerVersion:"0.6.24",globalThis:this};l.Object.freeze(ba);
l.Object.freeze(ba.semantics);var n=l.Math.imul||function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0},ca=l.Math.clz32||function(a){if(0===a)return 32;var b=1;0===(a&4294901760)&&(a<<=16,b+=16);0===(a&4278190080)&&(a<<=8,b+=8);0===(a&4026531840)&&(a<<=4,b+=4);0===(a&3221225472)&&(a<<=2,b+=2);return b+(a>>31)},da=0,ea=l.WeakMap?new l.WeakMap:null;function q(a){return function(b,c){return!(!b||!b.$classData||b.$classData.Q!==c||b.$classData.O!==a)}}
function fa(a){for(var b in a)return b}function ga(a,b,c){var d=new a.qa(b[c]);if(c<b.length-1){a=a.T;c+=1;for(var h=d.I,k=0;k<h.length;k++)h[k]=ga(a,b,c)}return d}function ha(a){return void 0===a?"undefined":a.toString()}
function ia(a){switch(typeof a){case "string":return r(ja);case "number":var b=a|0;return b===a?ka(b)?r(la):ma(b)?r(na):r(oa):"number"===typeof a?r(pa):r(qa);case "boolean":return r(ra);case "undefined":return r(sa);default:return null===a?a.$c():t(a)?r(ta):a&&a.$classData?r(a.$classData):null}}function ua(a,b){return a&&a.$classData||null===a?a.u(b):"number"===typeof a?"number"===typeof b&&(a===b?0!==a||1/a===1/b:a!==a&&b!==b):a===b}
function va(a){switch(typeof a){case "string":return u(v(),a);case "number":return wa(xa(),a);case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.$classData||null===a?a.s():null===ea?42:ya(a)}}function za(a,b){var c=l.Object.getPrototypeOf,d=l.Object.getOwnPropertyDescriptor;for(a=c(a);null!==a;){var h=d(a,b);if(void 0!==h)return h;a=c(a)}}function Aa(a,b,c){a=za(a,c);if(void 0!==a)return c=a.get,void 0!==c?c.call(b):a.value}
function Ba(a,b,c,d){a=za(a,c);if(void 0!==a&&(a=a.set,void 0!==a)){a.call(b,d);return}throw new l.TypeError("super has no setter '"+c+"'.");}
var ya=null!==ea?function(a){switch(typeof a){case "string":case "number":case "boolean":case "undefined":return va(a);default:if(null===a)return 0;var b=ea.get(a);void 0===b&&(da=b=da+1|0,ea.set(a,b));return b}}:function(a){if(a&&a.$classData){var b=a.$idHashCode$0;if(void 0!==b)return b;if(l.Object.isSealed(a))return 42;da=b=da+1|0;return a.$idHashCode$0=b}return null===a?0:va(a)};function ka(a){return"number"===typeof a&&a<<24>>24===a&&1/a!==1/-0}
function ma(a){return"number"===typeof a&&a<<16>>16===a&&1/a!==1/-0}function w(a){return null===a?x().$:a}function y(){this.ga=this.qa=void 0;this.O=this.T=this.d=null;this.Q=0;this.Ba=null;this.ca="";this.m=this.aa=this.ba=void 0;this.name="";this.isRawJSType=this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function z(a,b,c){var d=new y;d.d={};d.T=null;d.Ba=a;d.ca=b;d.m=function(){return!1};d.name=c;d.isPrimitive=!0;d.isInstance=function(){return!1};return d}
function A(a,b,c,d,h,k,f){var m=new y,p=fa(a);k=k||function(a){return!!(a&&a.$classData&&a.$classData.d[p])};f=f||function(a,b){return!!(a&&a.$classData&&a.$classData.Q===b&&a.$classData.O.d[p])};m.ga=h;m.d=c;m.ca="L"+b+";";m.m=f;m.name=b;m.isInterface=!1;m.isRawJSType=!!d;m.isInstance=k;return m}
function Ca(a){function b(a){if("number"===typeof a){this.I=Array(a);for(var b=0;b<a;b++)this.I[b]=h}else this.I=a}var c=new y,d=a.Ba,h="longZero"==d?x().$:d;b.prototype=new B;b.prototype.constructor=b;b.prototype.$classData=c;var d="["+a.ca,k=a.O||a,f=a.Q+1;c.qa=b;c.ga=Da;c.d={b:1,Ra:1,c:1};c.T=a;c.O=k;c.Q=f;c.Ba=null;c.ca=d;c.ba=void 0;c.aa=void 0;c.m=void 0;c.name=d;c.isPrimitive=!1;c.isInterface=!1;c.isArrayClass=!0;c.isInstance=function(a){return k.m(a,f)};return c}
function r(a){if(!a.ba){var b=new C;b.da=a;a.ba=b}return a.ba}function Ea(a){a.aa||(a.aa=Ca(a));return a.aa}y.prototype.getFakeInstance=function(){return this===ja?"some string":this===ra?!1:this===la||this===na||this===oa||this===pa||this===qa?0:this===ta?x().$:this===sa?void 0:{$classData:this}};y.prototype.getSuperclass=function(){return this.ga?r(this.ga):null};y.prototype.getComponentType=function(){return this.T?r(this.T):null};
y.prototype.newArrayOfThisClass=function(a){for(var b=this,c=0;c<a.length;c++)b=Ea(b);return ga(b,a,0)};var Fa=z(!1,"Z","boolean"),Ga=z(0,"C","char"),Ha=z(0,"B","byte"),Ia=z(0,"S","short"),Ja=z(0,"I","int"),Ka=z("longZero","J","long"),La=z(0,"F","float"),Ma=z(0,"D","double");Fa.m=q(Fa);Ga.m=q(Ga);Ha.m=q(Ha);Ia.m=q(Ia);Ja.m=q(Ja);Ka.m=q(Ka);La.m=q(La);Ma.m=q(Ma);function D(){}function B(){}B.prototype=D.prototype;D.prototype.a=function(){return this};D.prototype.u=function(a){return this===a};D.prototype.e=function(){var a=E(ia(this)),b=(+(this.s()>>>0)).toString(16);return a+"@"+b};D.prototype.s=function(){return ya(this)};D.prototype.toString=function(){return this.e()};var Da=A({b:0},"java.lang.Object",{b:1},void 0,void 0,function(a){return null!==a},function(a,b){if(a=a&&a.$classData){var c=a.Q||0;return!(c<b)&&(c>b||!a.O.isPrimitive)}return!1});
D.prototype.$classData=Da;function F(){this.Ea=0;this.Fa=null;this.na=0;this.ta=this.ma=null}F.prototype=new B;F.prototype.constructor=F;F.prototype.a=function(){Na=this;this.Ea=16;this.Fa="\u8c39\u6a2e\u6cf9\ub747\u180b\u1171\u996c\u05f5\u5ca7\ub095\u2326\u3348\u29ea\ua8f7\u31d4\u1a01\u0af7\u18ab\ud780\u7b8e";this.na=1577031886;this.ma="You are a dirty cheater and ";this.ta=Oa();return this};function Pa(a,b,c,d){Ra(c)>=Sa(d)&&(a=-1+Sa(d)|0,b.A(a));b=c.f?c.g:Ta(c);d=Sa(d);b.max=""+d}
function Xa(a){if(null===a)throw(new G).a();return a.f?a.g:Ya(a,Za().getElementById("form"))}function Sa(a){a=(a.f?a.g:$a(a)).value;a=(new H).t(a);return ab(bb(),a.q)}function Ra(a){a=(a.f?a.g:Ta(a)).value;a=(new H).t(a);return-1+ab(bb(),a.q)|0}function $a(a){if(null===a)throw(new G).a();return a.f?a.g:Ya(a,Za().getElementById("players"))}function Ta(a){if(null===a)throw(new G).a();return a.f?a.g:Ya(a,Za().getElementById("player"))}
function cb(a,b,c,d,h,k,f){Pa(0,b,k,f);(f.f?f.g:$a(f)).addEventListener("change",function(a,b,c){return function(){Pa(I(),a,b,c)}}(b,k,f),!1);(d.f?d.g:Xa(d)).addEventListener("submit",function(a,b,c,d){return function(f){I();f.preventDefault();f=I();var k,h=I(),X;if(b.f)X=b.g;else{if(null===b)throw(new G).a();X=b.f?b.g:Ya(b,Za().getElementById("seed"))}h=""+h.Fa+X.value;h=u(v(),h);k=(new J).C(h,h>>31);h=Ra(c);X=Sa(d);var Va=new db,Wa=-554899859^k.j;Va.xa=Wa>>>24|0|(65535&(5^k.i))<<8;Va.ya=16777215&
Wa;k=((eb(Va)+f.na|0)+h|0)%X|0;Wa=0===k;f.ta=(new K).o(fb(gb(),h-k|0,X));f=Wa?Oa():(new K).o(fb(gb(),eb(Va)+f.na|0,f.Ea));if(hb(f))f=a.A("Hello regular human. The tile number is "+(1+(f.N|0)|0)+".");else if(Oa()===f)f=a.A("You are the chameleon\u2026 good luck\u2026");else throw(new L).o(f);return f}}(c,h,k,f),!1)}F.prototype.$classData=A({vb:0},"net.michaelripley.chameleon.Chameleon$",{vb:1,b:1});var Na=void 0;function I(){Na||(Na=(new F).a());return Na}
function N(){this.Ha=this.qb=null;this.h=0}N.prototype=new B;N.prototype.constructor=N;N.prototype.a=function(){return this};function Za(){var a=ib();0===(268435456&a.h)&&0===(268435456&a.h)&&(a.Ha=jb(a).document,a.h|=268435456);return a.Ha}function jb(a){0===(134217728&a.h)&&0===(134217728&a.h)&&(a.qb=l.window,a.h|=134217728);return a.qb}N.prototype.$classData=A({wb:0},"org.scalajs.dom.package$",{wb:1,b:1});var kb=void 0;function ib(){kb||(kb=(new N).a());return kb}function C(){this.da=null}
C.prototype=new B;C.prototype.constructor=C;function E(a){return a.da.name}C.prototype.e=function(){return(this.da.isInterface?"interface ":this.da.isPrimitive?"":"class ")+E(this)};C.prototype.$classData=A({Hb:0},"java.lang.Class",{Hb:1,b:1});function lb(){}lb.prototype=new B;lb.prototype.constructor=lb;lb.prototype.a=function(){return this};function fb(a,b,c){a=b%c|0;return 0>b===0>c||0===a?a:a+c|0}lb.prototype.$classData=A({Qb:0},"java.lang.Math$",{Qb:1,b:1});var mb=void 0;
function gb(){mb||(mb=(new lb).a());return mb}function nb(){this.Ja=this.Va=null}nb.prototype=new B;nb.prototype.constructor=nb;nb.prototype.a=function(){ob=this;this.Va=pb(!1);this.Ja=pb(!0);return this};nb.prototype.$classData=A({Wb:0},"java.lang.System$",{Wb:1,b:1});var ob=void 0;function qb(){ob||(ob=(new nb).a());return ob}function rb(){}rb.prototype=new B;rb.prototype.constructor=rb;rb.prototype.a=function(){return this};rb.prototype.$classData=A({Xb:0},"java.util.Arrays$",{Xb:1,b:1});
var sb=void 0;function tb(){}tb.prototype=new B;tb.prototype.constructor=tb;function ub(){}ub.prototype=tb.prototype;function O(){this.la=null}O.prototype=new B;O.prototype.constructor=O;O.prototype.e=function(){return"DynamicVariable("+this.la+")"};O.prototype.o=function(a){this.la=a;return this};O.prototype.$classData=A({ic:0},"scala.util.DynamicVariable",{ic:1,b:1});function vb(){}vb.prototype=new B;vb.prototype.constructor=vb;function wb(){}wb.prototype=vb.prototype;
function xb(a,b){b=n(-862048943,b);b=n(461845907,b<<15|b>>>17|0);a^=b;return-430675100+n(5,a<<13|a>>>19|0)|0}function yb(a){a=n(-2048144789,a^(a>>>16|0));a=n(-1028477387,a^(a>>>13|0));return a^(a>>>16|0)}function zb(a){Ab();var b=a.ha();if(0===b)return a=a.ja(),u(v(),a);for(var c=-889275714,d=0;d<b;)c=xb(c,Cb(Db(),a.ia(d))),d=1+d|0;return yb(c^b)}
function Eb(a,b,c){var d=(new P).V(0);c=(new P).V(c);b.U(Fb(function(a,b,c){return function(a){c.k=xb(c.k,Cb(Db(),a));b.k=1+b.k|0}}(a,d,c)));return yb(c.k^d.k)}function Gb(){this.Ia=null}Gb.prototype=new B;Gb.prototype.constructor=Gb;Gb.prototype.a=function(){Hb=this;this.Ia=(new Q).a();return this};Gb.prototype.$classData=A({rc:0},"scala.collection.Iterator$",{rc:1,b:1});var Hb=void 0;function Ib(a,b,c){var d=(new R).a();return Jb(a,d,b,c).x.l}
function Jb(a,b,c,d){var h=Kb();Lb(b,c);a.U(Fb(function(a,b,c,d){return function(a){if(d.k)Mb(b,a),d.k=!1;else return Lb(b,c),Mb(b,a)}}(a,b,d,h)));Lb(b,")");return b}function Nb(){}Nb.prototype=new B;Nb.prototype.constructor=Nb;Nb.prototype.a=function(){return this};Nb.prototype.$classData=A({zc:0},"scala.collection.immutable.StringOps$",{zc:1,b:1});var Ob=void 0;function Pb(){this.H=!1;this.Ma=this.ea=this.P=null;this.oa=!1;this.Sa=this.Na=0}Pb.prototype=new B;Pb.prototype.constructor=Pb;
Pb.prototype.a=function(){Qb=this;this.P=(this.H=!!(l.ArrayBuffer&&l.Int32Array&&l.Float32Array&&l.Float64Array))?new l.ArrayBuffer(8):null;this.ea=this.H?new l.Int32Array(this.P,0,2):null;this.H&&new l.Float32Array(this.P,0,2);this.Ma=this.H?new l.Float64Array(this.P,0,1):null;if(this.H)this.ea[0]=16909060,a=1===((new l.Int8Array(this.P,0,8))[0]|0);else var a=!0;this.Na=(this.oa=a)?0:1;this.Sa=this.oa?1:0;return this};
function wa(a,b){var c=b|0;if(c===b&&-Infinity!==1/b)return c;if(a.H)a.Ma[0]=b,a=(new J).C(a.ea[a.Sa]|0,a.ea[a.Na]|0);else{if(b!==b)a=!1,b=2047,c=+l.Math.pow(2,51);else if(Infinity===b||-Infinity===b)a=0>b,b=2047,c=0;else if(0===b)a=-Infinity===1/b,c=b=0;else{var d=(a=0>b)?-b:b;if(d>=+l.Math.pow(2,-1022)){b=+l.Math.pow(2,52);var c=+l.Math.log(d)/.6931471805599453,c=+l.Math.floor(c)|0,c=1023>c?c:1023,h=+l.Math.pow(2,c);h>d&&(c=-1+c|0,h/=2);h=d/h*b;d=+l.Math.floor(h);h-=d;d=.5>h?d:.5<h?1+d:0!==d%2?
1+d:d;2<=d/b&&(c=1+c|0,d=1);1023<c?(c=2047,d=0):(c=1023+c|0,d-=b);b=c;c=d}else b=d/+l.Math.pow(2,-1074),c=+l.Math.floor(b),d=b-c,b=0,c=.5>d?c:.5<d?1+c:0!==c%2?1+c:c}c=+c;a=(new J).C(c|0,(a?-2147483648:0)|(b|0)<<20|c/4294967296|0)}return a.j^a.i}Pb.prototype.$classData=A({Mc:0},"scala.scalajs.runtime.Bits$",{Mc:1,b:1});var Qb=void 0;function xa(){Qb||(Qb=(new Pb).a());return Qb}function Rb(){this.h=!1}Rb.prototype=new B;Rb.prototype.constructor=Rb;Rb.prototype.a=function(){return this};
function u(a,b){a=0;for(var c=1,d=-1+(b.length|0)|0;0<=d;)a=a+n(65535&(b.charCodeAt(d)|0),c)|0,c=n(31,c),d=-1+d|0;return a}Rb.prototype.$classData=A({Oc:0},"scala.scalajs.runtime.RuntimeString$",{Oc:1,b:1});var Sb=void 0;function v(){Sb||(Sb=(new Rb).a());return Sb}function Tb(){}Tb.prototype=new B;Tb.prototype.constructor=Tb;Tb.prototype.a=function(){return this};function Ub(a,b){return b&&b.$classData&&b.$classData.d.F?b:(new Vb).o(b)}
Tb.prototype.$classData=A({Pc:0},"scala.scalajs.runtime.package$",{Pc:1,b:1});var Wb=void 0;function Xb(){Wb||(Wb=(new Tb).a());return Wb}function Yb(){}Yb.prototype=new B;Yb.prototype.constructor=Yb;Yb.prototype.a=function(){return this};function Zb(a,b){if($b(b))return a.r===b.r;if(ac(b)){if("number"===typeof b)return+b===a.r;if(t(b)){b=w(b);var c=b.i;a=a.r;return b.j===a&&c===a>>31}return null===b?null===a:ua(b,a)}return null===a&&null===b}
function bc(a,b,c){if(b===c)c=!0;else if(ac(b))a:if(ac(c))c=cc(b,c);else{if($b(c)){if("number"===typeof b){c=+b===c.r;break a}if(t(b)){a=w(b);b=a.i;c=c.r;c=a.j===c&&b===c>>31;break a}}c=null===b?null===c:ua(b,c)}else c=$b(b)?Zb(b,c):null===b?null===c:ua(b,c);return c}
function cc(a,b){if("number"===typeof a){a=+a;if("number"===typeof b)return a===+b;if(t(b)){var c=w(b);b=c.j;c=c.i;return a===dc(x(),b,c)}return b&&b.$classData&&b.$classData.d.hc?b.u(a):!1}if(t(a)){c=w(a);a=c.j;c=c.i;if(t(b)){b=w(b);var d=b.i;return a===b.j&&c===d}return"number"===typeof b?(b=+b,dc(x(),a,c)===b):b&&b.$classData&&b.$classData.d.hc?b.u((new J).C(a,c)):!1}return null===a?null===b:ua(a,b)}Yb.prototype.$classData=A({Sc:0},"scala.runtime.BoxesRunTime$",{Sc:1,b:1});var ec=void 0;
function fc(){ec||(ec=(new Yb).a());return ec}function gc(){}gc.prototype=new B;gc.prototype.constructor=gc;gc.prototype.a=function(){return this};gc.prototype.$classData=A({Vc:0},"scala.runtime.ScalaRunTime$",{Vc:1,b:1});var hc=void 0;function ic(){}ic.prototype=new B;ic.prototype.constructor=ic;ic.prototype.a=function(){return this};
function Cb(a,b){if(null===b)return 0;if("number"===typeof b){a=+b;b=2147483647<a?2147483647:-2147483648>a?-2147483648:a|0;if(b===a)a=b;else{b=x();var c;if(-9223372036854775808>a)b.ka=-2147483648,c=0;else if(0x7fffffffffffffff<=a)b.ka=2147483647,c=-1;else{c=a|0;var d=a/4294967296|0;b.ka=0>a&&0!==c?-1+d|0:d}b=b.ka;a=dc(x(),c,b)===a?c^b:wa(xa(),a)}return a}return t(b)?(a=w(b),b=(new J).C(a.j,a.i),a=b.j,b=b.i,b===a>>31?a:a^b):va(b)}ic.prototype.$classData=A({Xc:0},"scala.runtime.Statics$",{Xc:1,b:1});
var jc=void 0;function Db(){jc||(jc=(new ic).a());return jc}function kc(){}kc.prototype=new B;kc.prototype.constructor=kc;function lc(){}lc.prototype=kc.prototype;function ac(a){return!!(a&&a.$classData&&a.$classData.d.E||"number"===typeof a)}function S(){this.n=null}S.prototype=new B;S.prototype.constructor=S;function mc(){}mc.prototype=S.prototype;
S.prototype.La=function(){if(void 0===l.Error.captureStackTrace){try{var a={}.undef()}catch(b){if(a=Ub(Xb(),b),null!==a)if(nc(a))a=a.v;else throw Xb(),nc(a)?a.v:a;else throw b;}this.stackdata=a}else l.Error.captureStackTrace(this),this.stackdata=this;return this};S.prototype.sa=function(){return this.n};S.prototype.e=function(){var a=E(ia(this)),b=this.sa();return null===b?a:a+": "+b};S.prototype.D=function(a){this.n=a;this.La();return this};function db(){this.ya=this.xa=0}db.prototype=new B;
db.prototype.constructor=db;function eb(a){var b=a.ya,c=11+15525485*b,b=16777215&((c/16777216|0)+(16777215&(1502*b+15525485*a.xa|0))|0),c=16777215&(c|0);a.xa=b;a.ya=c;return(b<<8|c>>16)>>>0|0}db.prototype.$classData=A({Zb:0},"java.util.Random",{Zb:1,b:1,c:1});function oc(){this.za=0}oc.prototype=new wb;oc.prototype.constructor=oc;oc.prototype.a=function(){pc=this;this.za=u(v(),"Seq");u(v(),"Map");u(v(),"Set");return this};
function qc(a){var b=Ab();if(a&&a.$classData&&a.$classData.d.kd){for(b=b.za;!a.bd();)a.ad();a=yb(b^0)}else a=Eb(b,a,b.za);return a}oc.prototype.$classData=A({jc:0},"scala.util.hashing.MurmurHash3$",{jc:1,fd:1,b:1});var pc=void 0;function Ab(){pc||(pc=(new oc).a());return pc}function rc(){}rc.prototype=new B;rc.prototype.constructor=rc;function sc(){}sc.prototype=rc.prototype;rc.prototype.e=function(){return"\x3cfunction1\x3e"};function tc(){this.k=!1}tc.prototype=new B;tc.prototype.constructor=tc;
tc.prototype.e=function(){return""+this.k};function Kb(){var a=new tc;a.k=!0;return a}tc.prototype.$classData=A({Qc:0},"scala.runtime.BooleanRef",{Qc:1,b:1,c:1});var sa=A({Rc:0},"scala.runtime.BoxedUnit",{Rc:1,b:1,c:1},void 0,void 0,function(a){return void 0===a});function P(){this.k=0}P.prototype=new B;P.prototype.constructor=P;P.prototype.e=function(){return""+this.k};P.prototype.V=function(a){this.k=a;return this};P.prototype.$classData=A({Tc:0},"scala.runtime.IntRef",{Tc:1,b:1,c:1});
var ra=A({Eb:0},"java.lang.Boolean",{Eb:1,b:1,c:1,p:1},void 0,void 0,function(a){return"boolean"===typeof a});function T(){this.r=0}T.prototype=new B;T.prototype.constructor=T;T.prototype.u=function(a){return $b(a)?this.r===a.r:!1};T.prototype.e=function(){return l.String.fromCharCode(this.r)};function uc(a){var b=new T;b.r=a;return b}T.prototype.s=function(){return this.r};function $b(a){return!!(a&&a.$classData&&a.$classData.d.Qa)}
T.prototype.$classData=A({Qa:0},"java.lang.Character",{Qa:1,b:1,c:1,p:1});function vc(){this.Ta=null;this.h=0}vc.prototype=new B;vc.prototype.constructor=vc;vc.prototype.a=function(){return this};
function wc(a){if(0===(16&a.h)<<24>>24&&0===(16&a.h)<<24>>24){var b=new xc;b.B=[1632,1776,1984,2406,2534,2662,2790,2918,3046,3174,3302,3430,3664,3792,3872,4160,4240,6112,6160,6470,6608,6784,6800,6992,7088,7232,7248,42528,43216,43264,43472,43600,44016,65296,66720,69734,69872,69942,70096,71360,120782,120792,120802,120812,120822];for(var c=b.B.length|0,d=Ea(Ja),c=ga(d,[c],0),d=0,b=yc(b,b.B.length|0);b.w();){var h=b.G();c.I[d]=h|0;d=1+d|0}a.Ta=c;a.h=(16|a.h)<<24>>24}return a.Ta}
vc.prototype.$classData=A({Gb:0},"java.lang.Character$",{Gb:1,b:1,z:1,c:1});var zc=void 0;function Bc(){this.n=null}Bc.prototype=new mc;Bc.prototype.constructor=Bc;function Cc(){}Cc.prototype=Bc.prototype;function Dc(){}Dc.prototype=new B;Dc.prototype.constructor=Dc;Dc.prototype.a=function(){return this};function Ec(a){throw(new Fc).t('For input string: "'+a+'"');}
function ab(a,b){a=null===b?0:b.length|0;0===a&&Ec(b);var c=65535&(b.charCodeAt(0)|0),d=45===c,h=d?2147483648:2147483647,c=d||43===c?1:0;c>=(b.length|0)&&Ec(b);for(var k=0;c!==a;){zc||(zc=(new vc).a());var f;f=zc;var m=65535&(b.charCodeAt(c)|0);if(256>m)f=48<=m&&57>=m?-48+m|0:65<=m&&90>=m?-55+m|0:97<=m&&122>=m?-87+m|0:-1;else if(65313<=m&&65338>=m)f=-65303+m|0;else if(65345<=m&&65370>=m)f=-65335+m|0;else{sb||(sb=(new rb).a());var p;a:{p=wc(f);var Qa=m,M=0,Bb=p.I.length;for(;;){if(M===Bb){p=-1-M|0;
break a}var Ua=(M+Bb|0)>>>1|0,Ac=p.I[Ua];if(Qa<Ac)Bb=Ua;else{if(bc(fc(),Qa,Ac)){p=Ua;break a}M=1+Ua|0}}}p=0>p?-2-p|0:p;0>p?f=-1:(f=m-wc(f).I[p]|0,f=9<f?-1:f)}f=10>f?f:-1;k=10*k+f;(-1===f||k>h)&&Ec(b);c=1+c|0}return d?-k|0:k|0}Dc.prototype.$classData=A({Mb:0},"java.lang.Integer$",{Mb:1,b:1,z:1,c:1});var Gc=void 0;function bb(){Gc||(Gc=(new Dc).a());return Gc}function Hc(){this.ua=null}Hc.prototype=new ub;Hc.prototype.constructor=Hc;
Hc.prototype.a=function(){Ic=this;this.ua=(new O).o(qb().Va);(new O).o(qb().Ja);(new O).o(null);return this};Hc.prototype.$classData=A({ac:0},"scala.Console$",{ac:1,dd:1,b:1,ed:1});var Ic=void 0;function Jc(){Ic||(Ic=(new Hc).a());return Ic}function Kc(){this.Ka=null}Kc.prototype=new sc;Kc.prototype.constructor=Kc;Kc.prototype.A=function(a){return(0,this.Ka)(a)};function Fb(a){var b=new Kc;b.Ka=a;return b}Kc.prototype.$classData=A({Lc:0},"scala.scalajs.runtime.AnonFunction1",{Lc:1,rd:1,b:1,Da:1});
function Lc(){this.ka=0;this.$=null}Lc.prototype=new B;Lc.prototype.constructor=Lc;Lc.prototype.a=function(){Mc=this;this.$=(new J).C(0,0);return this};
function Nc(a,b){if(0===(-2097152&b))b=""+(4294967296*b+ +(a>>>0));else{var c=(32+ca(1E9)|0)-(0!==b?ca(b):32+ca(a)|0)|0,d=c,h=0===(32&d)?1E9<<d:0,d=0===(32&d)?5E8>>>(31-d|0)|0|0<<d:1E9<<d,k=a,f=b;for(a=b=0;0<=c&&0!==(-2097152&f);){var m=k,p=f,Qa=h,M=d;if(p===M?(-2147483648^m)>=(-2147483648^Qa):(-2147483648^p)>=(-2147483648^M))m=f,p=d,f=k-h|0,m=(-2147483648^f)>(-2147483648^k)?-1+(m-p|0)|0:m-p|0,k=f,f=m,32>c?b|=1<<c:a|=1<<c;c=-1+c|0;m=d>>>1|0;h=h>>>1|0|d<<31;d=m}c=f;if(0===c?-1147483648<=(-2147483648^
k):-2147483648<=(-2147483648^c))c=4294967296*f+ +(k>>>0),k=c/1E9,h=k/4294967296|0,d=b,b=k=d+(k|0)|0,a=(-2147483648^k)<(-2147483648^d)?1+(a+h|0)|0:a+h|0,k=c%1E9|0;c=""+k;b=""+(4294967296*a+ +(b>>>0))+"000000000".substring(c.length|0)+c}return b}function dc(a,b,c){return 0>c?-(4294967296*+((0!==b?~c:-c|0)>>>0)+ +((-b|0)>>>0)):4294967296*c+ +(b>>>0)}Lc.prototype.$classData=A({Nc:0},"scala.scalajs.runtime.RuntimeLong$",{Nc:1,b:1,z:1,c:1});var Mc=void 0;function x(){Mc||(Mc=(new Lc).a());return Mc}
function U(){this.f=!1;this.g=null}U.prototype=new B;U.prototype.constructor=U;U.prototype.a=function(){return this};U.prototype.e=function(){return"LazyRef "+(this.f?"of: "+this.g:"thunk")};function Ya(a,b){a.g=b;a.f=!0;return b}U.prototype.$classData=A({Uc:0},"scala.runtime.LazyRef",{Uc:1,b:1,z:1,c:1});function Oc(){}Oc.prototype=new B;Oc.prototype.constructor=Oc;function Pc(){}Pc.prototype=Oc.prototype;
var ja=A({xb:0},"java.lang.String",{xb:1,b:1,c:1,Pa:1,p:1},void 0,void 0,function(a){return"string"===typeof a}),la=A({Fb:0},"java.lang.Byte",{Fb:1,E:1,b:1,c:1,p:1},void 0,void 0,function(a){return ka(a)}),qa=A({Ib:0},"java.lang.Double",{Ib:1,E:1,b:1,c:1,p:1},void 0,void 0,function(a){return"number"===typeof a}),pa=A({Jb:0},"java.lang.Float",{Jb:1,E:1,b:1,c:1,p:1},void 0,void 0,function(a){return"number"===typeof a}),oa=A({Lb:0},"java.lang.Integer",{Lb:1,E:1,b:1,c:1,p:1},void 0,void 0,function(a){return"number"===
typeof a&&(a|0)===a&&1/a!==1/-0}),ta=A({Pb:0},"java.lang.Long",{Pb:1,E:1,b:1,c:1,p:1},void 0,void 0,function(a){return t(a)});function Qc(){this.n=null}Qc.prototype=new Cc;Qc.prototype.constructor=Qc;function V(){}V.prototype=Qc.prototype;var na=A({Ub:0},"java.lang.Short",{Ub:1,E:1,b:1,c:1,p:1},void 0,void 0,function(a){return ma(a)});function Rc(){this.l=null}Rc.prototype=new B;Rc.prototype.constructor=Rc;e=Rc.prototype;e.a=function(){this.l="";return this};e.e=function(){return this.l};
e.V=function(a){Rc.prototype.a.call(this);if(0>a)throw(new Sc).a();return this};e.y=function(){return this.l.length|0};e.$classData=A({Vb:0},"java.lang.StringBuilder",{Vb:1,b:1,Pa:1,Cb:1,c:1});function Tc(){}Tc.prototype=new B;Tc.prototype.constructor=Tc;function Uc(){}Uc.prototype=Tc.prototype;Tc.prototype.e=function(){return(this.w()?"non-empty":"empty")+" iterator"};Tc.prototype.U=function(a){for(;this.w();)a.A(this.G())};function J(){this.i=this.j=0}J.prototype=new lc;
J.prototype.constructor=J;e=J.prototype;e.u=function(a){return t(a)?this.j===a.j&&this.i===a.i:!1};e.e=function(){x();var a=this.j,b=this.i;return b===a>>31?""+a:0>b?"-"+Nc(-a|0,0!==a?~b:-b|0):Nc(a,b)};e.C=function(a,b){this.j=a;this.i=b;return this};e.V=function(a){J.prototype.C.call(this,a,a>>31);return this};e.s=function(){return this.j^this.i};function t(a){return!!(a&&a.$classData&&a.$classData.d.pb)}e.$classData=A({pb:0},"scala.scalajs.runtime.RuntimeLong",{pb:1,E:1,b:1,c:1,p:1});
function Vc(){}Vc.prototype=new Pc;Vc.prototype.constructor=Vc;function Wc(){}Wc.prototype=Vc.prototype;Vc.prototype.zb=function(){return this};function Xc(){this.n=null}Xc.prototype=new V;Xc.prototype.constructor=Xc;function Yc(){}Yc.prototype=Xc.prototype;function W(){this.n=null}W.prototype=new V;W.prototype.constructor=W;W.prototype.t=function(a){S.prototype.D.call(this,a);return this};W.prototype.$classData=A({Kb:0},"java.lang.IndexOutOfBoundsException",{Kb:1,M:1,L:1,F:1,b:1,c:1});
function Zc(){}Zc.prototype=new Pc;Zc.prototype.constructor=Zc;Zc.prototype.a=function(){return this};Zc.prototype.$classData=A({Ob:0},"java.lang.JSConsoleBasedPrintStream$DummyOutputStream",{Ob:1,ub:1,b:1,sb:1,Db:1,tb:1});function Sc(){this.n=null}Sc.prototype=new V;Sc.prototype.constructor=Sc;Sc.prototype.a=function(){S.prototype.D.call(this,null);return this};Sc.prototype.$classData=A({Rb:0},"java.lang.NegativeArraySizeException",{Rb:1,M:1,L:1,F:1,b:1,c:1});function G(){this.n=null}
G.prototype=new V;G.prototype.constructor=G;G.prototype.a=function(){S.prototype.D.call(this,null);return this};G.prototype.$classData=A({Sb:0},"java.lang.NullPointerException",{Sb:1,M:1,L:1,F:1,b:1,c:1});function $c(){this.n=null}$c.prototype=new V;$c.prototype.constructor=$c;$c.prototype.t=function(a){S.prototype.D.call(this,a);return this};$c.prototype.$classData=A({Yb:0},"java.util.NoSuchElementException",{Yb:1,M:1,L:1,F:1,b:1,c:1});function L(){this.W=this.Ua=this.n=null;this.pa=!1}
L.prototype=new V;L.prototype.constructor=L;L.prototype.sa=function(){if(!this.pa&&!this.pa){var a;if(null===this.W)a="null";else try{a=ha(this.W)+" ("+("of class "+E(ia(this.W)))+")"}catch(b){if(null!==Ub(Xb(),b))a="an instance of class "+E(ia(this.W));else throw b;}this.Ua=a;this.pa=!0}return this.Ua};L.prototype.o=function(a){this.W=a;S.prototype.D.call(this,null);return this};L.prototype.$classData=A({bc:0},"scala.MatchError",{bc:1,M:1,L:1,F:1,b:1,c:1});function ad(){}ad.prototype=new B;
ad.prototype.constructor=ad;function bd(){}bd.prototype=ad.prototype;function Q(){}Q.prototype=new Uc;Q.prototype.constructor=Q;Q.prototype.a=function(){return this};Q.prototype.G=function(){throw(new $c).t("next on empty iterator");};Q.prototype.w=function(){return!1};Q.prototype.$classData=A({sc:0},"scala.collection.Iterator$$anon$2",{sc:1,Za:1,b:1,hb:1,Z:1,Y:1});function Y(){this.Ga=this.S=0;this.rb=null}Y.prototype=new Uc;Y.prototype.constructor=Y;
Y.prototype.G=function(){var a=this.rb.ia(this.S);this.S=1+this.S|0;return a};function cd(a){var b=new Y;b.rb=a;b.S=0;b.Ga=a.ha();return b}Y.prototype.w=function(){return this.S<this.Ga};Y.prototype.$classData=A({Wc:0},"scala.runtime.ScalaRunTime$$anon$1",{Wc:1,Za:1,b:1,hb:1,Z:1,Y:1});function Fc(){this.n=null}Fc.prototype=new Yc;Fc.prototype.constructor=Fc;Fc.prototype.t=function(a){S.prototype.D.call(this,a);return this};
Fc.prototype.$classData=A({Tb:0},"java.lang.NumberFormatException",{Tb:1,cd:1,M:1,L:1,F:1,b:1,c:1});function dd(){}dd.prototype=new bd;dd.prototype.constructor=dd;e=dd.prototype;e.a=function(){return this};e.ja=function(){return"None"};e.ha=function(){return 0};e.ia=function(a){throw(new W).t(""+a);};e.e=function(){return"None"};e.s=function(){return 2433880};e.va=function(){return cd(this)};e.$classData=A({dc:0},"scala.None$",{dc:1,ec:1,b:1,Xa:1,X:1,z:1,c:1});var ed=void 0;
function Oa(){ed||(ed=(new dd).a());return ed}function K(){this.N=null}K.prototype=new bd;K.prototype.constructor=K;e=K.prototype;e.ja=function(){return"Some"};e.ha=function(){return 1};e.u=function(a){return this===a?!0:hb(a)?bc(fc(),this.N,a.N):!1};e.ia=function(a){switch(a){case 0:return this.N;default:throw(new W).t(""+a);}};e.e=function(){hc||(hc=(new gc).a());var a=this.va();return Ib(a,this.ja()+"(",",")};e.o=function(a){this.N=a;return this};e.s=function(){return zb(this)};e.va=function(){return cd(this)};
function hb(a){return!!(a&&a.$classData&&a.$classData.d.Ya)}e.$classData=A({Ya:0},"scala.Some",{Ya:1,ec:1,b:1,Xa:1,X:1,z:1,c:1});
function fd(a){a=E(ia(a.Wa()));for(var b=-1+(a.length|0)|0;;)if(-1!==b&&36===(65535&(a.charCodeAt(b)|0)))b=-1+b|0;else break;if(-1===b||46===(65535&(a.charCodeAt(b)|0)))return"";for(var c="";;){for(var d=1+b|0;;)if(-1!==b&&57>=(65535&(a.charCodeAt(b)|0))&&48<=(65535&(a.charCodeAt(b)|0)))b=-1+b|0;else break;for(var h=b;;)if(-1!==b&&36!==(65535&(a.charCodeAt(b)|0))&&46!==(65535&(a.charCodeAt(b)|0)))b=-1+b|0;else break;var k=1+b|0;if(b===h&&d!==(a.length|0))return c;for(;;)if(-1!==b&&36===(65535&(a.charCodeAt(b)|
0)))b=-1+b|0;else break;var h=-1===b?!0:46===(65535&(a.charCodeAt(b)|0)),f;(f=h)||(f=65535&(a.charCodeAt(k)|0),f=!(90<f&&127>f||65>f));if(f){d=a.substring(k,d);k=c;if(null===k)throw(new G).a();c=""===k?d:""+d+uc(46)+c;if(h)return c}}}function gd(){}gd.prototype=new Wc;gd.prototype.constructor=gd;function hd(){}hd.prototype=gd.prototype;gd.prototype.Ab=function(){Vc.prototype.zb.call(this);return this};function id(){this.R=this.Oa=null}id.prototype=new hd;id.prototype.constructor=id;
function pb(a){var b=new id;b.Oa=a;(new Zc).a();gd.prototype.Ab.call(b);b.R="";return b}function jd(a,b){for(;""!==b;){var c=b.indexOf("\n")|0;if(0>c)a.R=""+a.R+b,b="";else{var d=""+a.R+b.substring(0,c);l.console&&(a.Oa&&l.console.error?l.console.error(d):l.console.log(d));a.R="";b=b.substring(1+c|0)}}}id.prototype.$classData=A({Nb:0},"java.lang.JSConsoleBasedPrintStream",{Nb:1,Zc:1,Yc:1,ub:1,b:1,sb:1,Db:1,tb:1,Cb:1});function Z(){this.K=this.ra=0;this.Ca=null}Z.prototype=new Uc;
Z.prototype.constructor=Z;Z.prototype.G=function(){this.K>=this.ra&&(Hb||(Hb=(new Gb).a()),Hb.Ia.G());var a=this.Ca.J(this.K);this.K=1+this.K|0;return a};function yc(a,b){var c=new Z;c.ra=b;if(null===a)throw Xb(),nc(null)?null.v:null;c.Ca=a;c.K=0;return c}Z.prototype.w=function(){return this.K<this.ra};Z.prototype.$classData=A({pc:0},"scala.collection.IndexedSeqLike$Elements",{pc:1,Za:1,b:1,hb:1,Z:1,Y:1,gd:1,z:1,c:1});function Vb(){this.v=this.n=null}Vb.prototype=new V;Vb.prototype.constructor=Vb;
e=Vb.prototype;e.ja=function(){return"JavaScriptException"};e.ha=function(){return 1};e.La=function(){this.stackdata=this.v;return this};e.u=function(a){return this===a?!0:nc(a)?bc(fc(),this.v,a.v):!1};e.ia=function(a){switch(a){case 0:return this.v;default:throw(new W).t(""+a);}};e.sa=function(){return ha(this.v)};e.o=function(a){this.v=a;S.prototype.D.call(this,null);return this};e.s=function(){return zb(this)};e.va=function(){return cd(this)};
function nc(a){return!!(a&&a.$classData&&a.$classData.d.ob)}e.$classData=A({ob:0},"scala.scalajs.js.JavaScriptException",{ob:1,M:1,L:1,F:1,b:1,c:1,Xa:1,X:1,z:1});function kd(){}kd.prototype=new B;kd.prototype.constructor=kd;function ld(){}ld.prototype=kd.prototype;kd.prototype.Wa=function(){return this};kd.prototype.Aa=function(){return fd(this)};
function md(a,b){if(b&&b.$classData&&b.$classData.d.db){var c=a.y();if(c===b.y()){for(var d=0;d<c&&bc(fc(),a.J(d),b.J(d));)d=1+d|0;return d===c}return!1}a:{a=a.fa();for(b=b.fa();a.w()&&b.w();)if(!bc(fc(),a.G(),b.G())){b=!1;break a}b=!a.w()&&!b.w()}return b}function nd(a,b){for(var c=0,d=a.y();c<d;)b.A(a.J(c)),c=1+c|0}function od(){}od.prototype=new ld;od.prototype.constructor=od;function pd(){}pd.prototype=od.prototype;function H(){this.q=null}H.prototype=new B;H.prototype.constructor=H;e=H.prototype;
e.J=function(a){a=65535&(this.q.charCodeAt(a)|0);return uc(a)};e.wa=function(a){return md(this,a)};e.u=function(a){Ob||(Ob=(new Nb).a());return a&&a.$classData&&a.$classData.d.nb?this.q===(null===a?null:a.q):!1};e.e=function(){return this.q};e.U=function(a){nd(this,a)};e.fa=function(){return yc(this,this.q.length|0)};e.y=function(){return this.q.length|0};e.Wa=function(){return this.q};e.t=function(a){this.q=a;return this};e.s=function(){var a=this.q;return u(v(),a)};e.Aa=function(){return fd(this)};
e.$classData=A({nb:0},"scala.collection.immutable.StringOps",{nb:1,b:1,yc:1,fb:1,eb:1,jb:1,gb:1,X:1,kb:1,mb:1,lb:1,Z:1,Y:1,cb:1,ib:1,$a:1,bb:1,gc:1,p:1});function qd(){}qd.prototype=new pd;qd.prototype.constructor=qd;function rd(){}rd.prototype=qd.prototype;qd.prototype.u=function(a){return a&&a.$classData&&a.$classData.d.ab?this.wa(a):!1};qd.prototype.e=function(){var a=this.Aa()+"(";return Ib(this,a,", ")};function sd(){}sd.prototype=new rd;sd.prototype.constructor=sd;function td(){}
td.prototype=sd.prototype;function ud(){}ud.prototype=new td;ud.prototype.constructor=ud;function vd(){}vd.prototype=ud.prototype;function R(){this.x=null}R.prototype=new td;R.prototype.constructor=R;e=R.prototype;e.a=function(){R.prototype.yb.call(this,16,"");return this};e.J=function(a){a=65535&(this.x.l.charCodeAt(a)|0);return uc(a)};e.A=function(a){a=65535&(this.x.l.charCodeAt(a|0)|0);return uc(a)};e.wa=function(a){return md(this,a)};e.e=function(){return this.x.l};e.U=function(a){nd(this,a)};
e.fa=function(){return yc(this,this.x.y())};function Lb(a,b){a=a.x;a.l=""+a.l+b}e.yb=function(a,b){a=(new Rc).V((b.length|0)+a|0);a.l=""+a.l+b;R.prototype.Bb.call(this,a);return this};e.y=function(){return this.x.y()};e.Bb=function(a){this.x=a;return this};function Mb(a,b){var c=a.x;c.l+=""+b;return a}e.s=function(){return qc(this)};
e.$classData=A({Ic:0},"scala.collection.mutable.StringBuilder",{Ic:1,Ac:1,lc:1,kc:1,mc:1,b:1,uc:1,kb:1,mb:1,lb:1,Z:1,Y:1,cb:1,ib:1,oc:1,wc:1,qc:1,nc:1,$a:1,gb:1,X:1,tc:1,fc:1,Da:1,ab:1,bb:1,jb:1,Gc:1,Fc:1,Jc:1,cc:1,Hc:1,Cc:1,$b:1,Ra:1,Pa:1,Dc:1,db:1,eb:1,Ec:1,yc:1,fb:1,gc:1,p:1,qd:1,Bc:1,xc:1,vc:1,z:1,c:1});function xc(){this.B=null}xc.prototype=new vd;xc.prototype.constructor=xc;e=xc.prototype;e.J=function(a){return this.B[a]};e.A=function(a){return this.B[a|0]};e.wa=function(a){return md(this,a)};
e.U=function(a){nd(this,a)};e.fa=function(){return yc(this,this.B.length|0)};e.y=function(){return this.B.length|0};e.s=function(){return qc(this)};e.Aa=function(){return"WrappedArray"};e.$classData=A({Kc:0},"scala.scalajs.js.WrappedArray",{Kc:1,ld:1,Ac:1,lc:1,kc:1,mc:1,b:1,uc:1,kb:1,mb:1,lb:1,Z:1,Y:1,cb:1,ib:1,oc:1,wc:1,qc:1,nc:1,$a:1,gb:1,X:1,tc:1,fc:1,Da:1,ab:1,bb:1,jb:1,Gc:1,Fc:1,Jc:1,cc:1,Hc:1,Cc:1,$b:1,Ra:1,nd:1,od:1,xc:1,vc:1,id:1,hd:1,jd:1,Dc:1,db:1,eb:1,Ec:1,md:1,pd:1,fb:1,Bc:1});
aa.cheat=function(){var a=I(),b=a.ta;if(hb(b))a=a.ma+"the chameleon was player "+(1+(b.N|0)|0),jd(Jc().ua.la,a+"\n");else if(Oa()===b)a=a.ma+"you haven't even played a game yet",jd(Jc().ua.la,a+"\n");else throw(new L).o(b);};var wd=I(),xd;xd=new (Ea(ja).qa)([]);
(function(a){var b=(new U).a(),c=(new U).a(),d=(new U).a(),h=(new U).a(),k=(new U).a(),f=Fb(function(a,b){return function(a){a|=0;(b.f?b.g:Ta(b)).value=""+(1+a|0)}}(a,h));a=Fb(function(a,b){return function(a){var c;if(b.f)c=b.g;else{if(null===b)throw(new G).a();c=b.f?b.g:Ya(b,Za().getElementById("out"))}c.innerHTML=a}}(a,c));jb(ib()).addEventListener("load",function(a,b,c,d,f,h){return function(){cb(I(),a,b,c,d,f,h)}}(f,a,b,d,h,k),!1)})(wd,xd);
}).call(this);
